[package]
name = "sodigy-test-viewer"
version = "0.1.0"
edition = "2024"

[dependencies]
ragit-fs = "0.4.5"
regex = "*"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
shev = { path = "../../" }
